[general]
debug=0
database_url='sqlite:///var/lib/lrcp/db.sqlite3'
secret_key=''

[api]
url='http://127.0.0.1:8000'
access_token_expire_minuts=30

[master]
host='127.0.0.1'
port=4051

[client]
host='127.0.0.1'
port=4052
api_key=''
