"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class BaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    API_KEY_FIELD_NUMBER: builtins.int
    api_key: typing.Text
    def __init__(self,
        *,
        api_key: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key",b"api_key"]) -> None: ...
global___BaseRequest = BaseRequest

class BaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ErrorCodes:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ErrorCodesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BaseResponse._ErrorCodes.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NEED_CPU_INFO: BaseResponse._ErrorCodes.ValueType  # 0
    class ErrorCodes(_ErrorCodes, metaclass=_ErrorCodesEnumTypeWrapper):
        pass

    NEED_CPU_INFO: BaseResponse.ErrorCodes.ValueType  # 0

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_code: global___BaseResponse.ErrorCodes.ValueType
    error_message: typing.Text
    def __init__(self,
        *,
        success: builtins.bool = ...,
        error_code: global___BaseResponse.ErrorCodes.ValueType = ...,
        error_message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_code",b"error_code","error_message",b"error_message","success",b"success"]) -> None: ...
global___BaseResponse = BaseResponse
