# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lrcp/grpc_data/base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19lrcp/grpc_data/base.proto\"\x1e\n\x0b\x42\x61seRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"\x85\x01\n\x0c\x42\x61seResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12,\n\nerror_code\x18\x02 \x01(\x0e\x32\x18.BaseResponse.ErrorCodes\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x1f\n\nErrorCodes\x12\x11\n\rNEED_CPU_INFO\x10\x00\x62\x06proto3')



_BASEREQUEST = DESCRIPTOR.message_types_by_name['BaseRequest']
_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
_BASERESPONSE_ERRORCODES = _BASERESPONSE.enum_types_by_name['ErrorCodes']
BaseRequest = _reflection.GeneratedProtocolMessageType('BaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEREQUEST,
  '__module__' : 'lrcp.grpc_data.base_pb2'
  # @@protoc_insertion_point(class_scope:BaseRequest)
  })
_sym_db.RegisterMessage(BaseRequest)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'lrcp.grpc_data.base_pb2'
  # @@protoc_insertion_point(class_scope:BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASEREQUEST._serialized_start=29
  _BASEREQUEST._serialized_end=59
  _BASERESPONSE._serialized_start=62
  _BASERESPONSE._serialized_end=195
  _BASERESPONSE_ERRORCODES._serialized_start=164
  _BASERESPONSE_ERRORCODES._serialized_end=195
# @@protoc_insertion_point(module_scope)
