"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import lrcp.grpc_data.base_pb2
import lrcp.grpc_data.client_pb2

class ClientServicerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Ping: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.base_pb2.BaseResponse]

    GetSystemInfo: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.client_pb2.GetSystemInfoResponse]

    GetMemoryInfo: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.base_pb2.GetMemoryInfoResponse]

    GetCPUInfo: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.base_pb2.GetCPUInfoResponse]

    GetNetInfo: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.base_pb2.GetNetInfoResponse]


class ClientServicerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Ping(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.base_pb2.BaseResponse: ...

    @abc.abstractmethod
    def GetSystemInfo(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.client_pb2.GetSystemInfoResponse: ...

    @abc.abstractmethod
    def GetMemoryInfo(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.base_pb2.GetMemoryInfoResponse: ...

    @abc.abstractmethod
    def GetCPUInfo(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.base_pb2.GetCPUInfoResponse: ...

    @abc.abstractmethod
    def GetNetInfo(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.base_pb2.GetNetInfoResponse: ...


def add_ClientServicerServicer_to_server(servicer: ClientServicerServicer, server: grpc.Server) -> None: ...
