"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetSystemInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OS_NAME_FIELD_NUMBER: builtins.int
    OS_RELEASE_FIELD_NUMBER: builtins.int
    UPTIME_FIELD_NUMBER: builtins.int
    os_name: typing.Text
    os_release: typing.Text
    uptime: builtins.float
    def __init__(self,
        *,
        os_name: typing.Text = ...,
        os_release: typing.Text = ...,
        uptime: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["os_name",b"os_name","os_release",b"os_release","uptime",b"uptime"]) -> None: ...
global___GetSystemInfoResponse = GetSystemInfoResponse

class GetMemoryInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MEM_TOTAL_FIELD_NUMBER: builtins.int
    MEM_FREE_FIELD_NUMBER: builtins.int
    MEM_AVAILABLE_FIELD_NUMBER: builtins.int
    BUFFERS_FIELD_NUMBER: builtins.int
    CACHED_FIELD_NUMBER: builtins.int
    SWAP_CACHED_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    INACTIVE_FIELD_NUMBER: builtins.int
    ACTIVE_ANON_FIELD_NUMBER: builtins.int
    INACTIVE_ANON_FIELD_NUMBER: builtins.int
    ACTIVE_FILE_FIELD_NUMBER: builtins.int
    INACTIVE_FILE_FIELD_NUMBER: builtins.int
    UNEVICTABLE_FIELD_NUMBER: builtins.int
    MLOCKED_FIELD_NUMBER: builtins.int
    SWAP_TOTAL_FIELD_NUMBER: builtins.int
    SWAP_FREE_FIELD_NUMBER: builtins.int
    DIRTY_FIELD_NUMBER: builtins.int
    WRITEBACK_FIELD_NUMBER: builtins.int
    ANON_PAGES_FIELD_NUMBER: builtins.int
    MAPPED_FIELD_NUMBER: builtins.int
    SHMEM_FIELD_NUMBER: builtins.int
    KRECLAIMABLE_FIELD_NUMBER: builtins.int
    SLAB_FIELD_NUMBER: builtins.int
    SRECLAIMABLE_FIELD_NUMBER: builtins.int
    SUNRECLAIM_FIELD_NUMBER: builtins.int
    KERNEL_STACK_FIELD_NUMBER: builtins.int
    PAGE_TABLES_FIELD_NUMBER: builtins.int
    NFS_UNSTABLE_FIELD_NUMBER: builtins.int
    BOUNCE_FIELD_NUMBER: builtins.int
    WRITEBACK_TMP_FIELD_NUMBER: builtins.int
    COMMIT_LIMIT_FIELD_NUMBER: builtins.int
    COMMITTED_AS_FIELD_NUMBER: builtins.int
    VMALLOC_TOTAL_FIELD_NUMBER: builtins.int
    VMALLOC_USED_FIELD_NUMBER: builtins.int
    VMALLOC_CHUNK_FIELD_NUMBER: builtins.int
    PERCPU_FIELD_NUMBER: builtins.int
    HARDWARE_CORRUPTED_FIELD_NUMBER: builtins.int
    ANON_HUGE_PAGES_FIELD_NUMBER: builtins.int
    SHMEM_HUGE_PAGES_FIELD_NUMBER: builtins.int
    SHMEM_PMD_MAPPED_FIELD_NUMBER: builtins.int
    FILE_HUGE_PAGES_FIELD_NUMBER: builtins.int
    FILE_PMD_MAPPED_FIELD_NUMBER: builtins.int
    HUGE_PAGES_TOTAL_FIELD_NUMBER: builtins.int
    HUGE_PAGES_FREE_FIELD_NUMBER: builtins.int
    HUGE_PAGES_RSVD_FIELD_NUMBER: builtins.int
    HUGE_PAGES_SURP_FIELD_NUMBER: builtins.int
    HUGEPAGESIZE_FIELD_NUMBER: builtins.int
    HUGETLB_FIELD_NUMBER: builtins.int
    DIRECT_MAP_4K_FIELD_NUMBER: builtins.int
    DIRECT_MAP_2M_FIELD_NUMBER: builtins.int
    DIRECT_MAP_1G_FIELD_NUMBER: builtins.int
    mem_total: builtins.int
    mem_free: builtins.int
    mem_available: builtins.int
    buffers: builtins.int
    cached: builtins.int
    swap_cached: builtins.int
    active: builtins.int
    inactive: builtins.int
    active_anon: builtins.int
    inactive_anon: builtins.int
    active_file: builtins.int
    inactive_file: builtins.int
    unevictable: builtins.int
    mlocked: builtins.int
    swap_total: builtins.int
    swap_free: builtins.int
    dirty: builtins.int
    writeback: builtins.int
    anon_pages: builtins.int
    mapped: builtins.int
    shmem: builtins.int
    kreclaimable: builtins.int
    slab: builtins.int
    sreclaimable: builtins.int
    sunreclaim: builtins.int
    kernel_stack: builtins.int
    page_tables: builtins.int
    nfs_unstable: builtins.int
    bounce: builtins.int
    writeback_tmp: builtins.int
    commit_limit: builtins.int
    committed_as: builtins.int
    vmalloc_total: builtins.int
    vmalloc_used: builtins.int
    vmalloc_chunk: builtins.int
    percpu: builtins.int
    hardware_corrupted: builtins.int
    anon_huge_pages: builtins.int
    shmem_huge_pages: builtins.int
    shmem_pmd_mapped: builtins.int
    file_huge_pages: builtins.int
    file_pmd_mapped: builtins.int
    huge_pages_total: builtins.int
    huge_pages_free: builtins.int
    huge_pages_rsvd: builtins.int
    huge_pages_surp: builtins.int
    hugepagesize: builtins.int
    hugetlb: builtins.int
    direct_map_4k: builtins.int
    direct_map_2m: builtins.int
    direct_map_1g: builtins.int
    def __init__(self,
        *,
        mem_total: builtins.int = ...,
        mem_free: builtins.int = ...,
        mem_available: builtins.int = ...,
        buffers: builtins.int = ...,
        cached: builtins.int = ...,
        swap_cached: builtins.int = ...,
        active: builtins.int = ...,
        inactive: builtins.int = ...,
        active_anon: builtins.int = ...,
        inactive_anon: builtins.int = ...,
        active_file: builtins.int = ...,
        inactive_file: builtins.int = ...,
        unevictable: builtins.int = ...,
        mlocked: builtins.int = ...,
        swap_total: builtins.int = ...,
        swap_free: builtins.int = ...,
        dirty: builtins.int = ...,
        writeback: builtins.int = ...,
        anon_pages: builtins.int = ...,
        mapped: builtins.int = ...,
        shmem: builtins.int = ...,
        kreclaimable: builtins.int = ...,
        slab: builtins.int = ...,
        sreclaimable: builtins.int = ...,
        sunreclaim: builtins.int = ...,
        kernel_stack: builtins.int = ...,
        page_tables: builtins.int = ...,
        nfs_unstable: builtins.int = ...,
        bounce: builtins.int = ...,
        writeback_tmp: builtins.int = ...,
        commit_limit: builtins.int = ...,
        committed_as: builtins.int = ...,
        vmalloc_total: builtins.int = ...,
        vmalloc_used: builtins.int = ...,
        vmalloc_chunk: builtins.int = ...,
        percpu: builtins.int = ...,
        hardware_corrupted: builtins.int = ...,
        anon_huge_pages: builtins.int = ...,
        shmem_huge_pages: builtins.int = ...,
        shmem_pmd_mapped: builtins.int = ...,
        file_huge_pages: builtins.int = ...,
        file_pmd_mapped: builtins.int = ...,
        huge_pages_total: builtins.int = ...,
        huge_pages_free: builtins.int = ...,
        huge_pages_rsvd: builtins.int = ...,
        huge_pages_surp: builtins.int = ...,
        hugepagesize: builtins.int = ...,
        hugetlb: builtins.int = ...,
        direct_map_4k: builtins.int = ...,
        direct_map_2m: builtins.int = ...,
        direct_map_1g: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["active",b"active","active_anon",b"active_anon","active_file",b"active_file","anon_huge_pages",b"anon_huge_pages","anon_pages",b"anon_pages","bounce",b"bounce","buffers",b"buffers","cached",b"cached","commit_limit",b"commit_limit","committed_as",b"committed_as","direct_map_1g",b"direct_map_1g","direct_map_2m",b"direct_map_2m","direct_map_4k",b"direct_map_4k","dirty",b"dirty","file_huge_pages",b"file_huge_pages","file_pmd_mapped",b"file_pmd_mapped","hardware_corrupted",b"hardware_corrupted","huge_pages_free",b"huge_pages_free","huge_pages_rsvd",b"huge_pages_rsvd","huge_pages_surp",b"huge_pages_surp","huge_pages_total",b"huge_pages_total","hugepagesize",b"hugepagesize","hugetlb",b"hugetlb","inactive",b"inactive","inactive_anon",b"inactive_anon","inactive_file",b"inactive_file","kernel_stack",b"kernel_stack","kreclaimable",b"kreclaimable","mapped",b"mapped","mem_available",b"mem_available","mem_free",b"mem_free","mem_total",b"mem_total","mlocked",b"mlocked","nfs_unstable",b"nfs_unstable","page_tables",b"page_tables","percpu",b"percpu","shmem",b"shmem","shmem_huge_pages",b"shmem_huge_pages","shmem_pmd_mapped",b"shmem_pmd_mapped","slab",b"slab","sreclaimable",b"sreclaimable","sunreclaim",b"sunreclaim","swap_cached",b"swap_cached","swap_free",b"swap_free","swap_total",b"swap_total","unevictable",b"unevictable","vmalloc_chunk",b"vmalloc_chunk","vmalloc_total",b"vmalloc_total","vmalloc_used",b"vmalloc_used","writeback",b"writeback","writeback_tmp",b"writeback_tmp"]) -> None: ...
global___GetMemoryInfoResponse = GetMemoryInfoResponse

class GetCPUInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class CPUCore(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        PROCESSOR_FIELD_NUMBER: builtins.int
        VENDOR_ID_FIELD_NUMBER: builtins.int
        CPU_FAMILY_FIELD_NUMBER: builtins.int
        MODEL_FIELD_NUMBER: builtins.int
        MODEL_NAME_FIELD_NUMBER: builtins.int
        STEPPING_FIELD_NUMBER: builtins.int
        MICROCODE_FIELD_NUMBER: builtins.int
        CPU_MHZ_FIELD_NUMBER: builtins.int
        CACHE_SIZE_FIELD_NUMBER: builtins.int
        PHYSICAL_ID_FIELD_NUMBER: builtins.int
        SIBLINGS_FIELD_NUMBER: builtins.int
        CORE_ID_FIELD_NUMBER: builtins.int
        CPU_CORES_FIELD_NUMBER: builtins.int
        APICID_FIELD_NUMBER: builtins.int
        INITIAL_APICID_FIELD_NUMBER: builtins.int
        FPU_FIELD_NUMBER: builtins.int
        FPU_EXCEPTION_FIELD_NUMBER: builtins.int
        CPUID_LEVEL_FIELD_NUMBER: builtins.int
        WP_FIELD_NUMBER: builtins.int
        FLAGS_FIELD_NUMBER: builtins.int
        BUGS_FIELD_NUMBER: builtins.int
        BOGOMIPS_FIELD_NUMBER: builtins.int
        TLB_SIZE_FIELD_NUMBER: builtins.int
        CLFLUSH_SIZE_FIELD_NUMBER: builtins.int
        CACHE_ALIGNMENT_FIELD_NUMBER: builtins.int
        ADDRESS_SIZES_FIELD_NUMBER: builtins.int
        POWER_MANAGEMENT_FIELD_NUMBER: builtins.int
        processor: builtins.int
        vendor_id: typing.Text
        cpu_family: builtins.int
        model: builtins.int
        model_name: typing.Text
        stepping: builtins.int
        microcode: typing.Text
        cpu_mhz: typing.Text
        cache_size: builtins.int
        physical_id: builtins.int
        siblings: builtins.int
        core_id: builtins.int
        cpu_cores: builtins.int
        apicid: builtins.int
        initial_apicid: builtins.int
        fpu: builtins.bool
        fpu_exception: builtins.bool
        cpuid_level: builtins.int
        wp: builtins.bool
        @property
        def flags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        @property
        def bugs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        bogomips: builtins.float
        tlb_size: typing.Text
        clflush_size: builtins.int
        cache_alignment: builtins.int
        @property
        def address_sizes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        @property
        def power_management(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        def __init__(self,
            *,
            processor: builtins.int = ...,
            vendor_id: typing.Text = ...,
            cpu_family: builtins.int = ...,
            model: builtins.int = ...,
            model_name: typing.Text = ...,
            stepping: builtins.int = ...,
            microcode: typing.Text = ...,
            cpu_mhz: typing.Text = ...,
            cache_size: builtins.int = ...,
            physical_id: builtins.int = ...,
            siblings: builtins.int = ...,
            core_id: builtins.int = ...,
            cpu_cores: builtins.int = ...,
            apicid: builtins.int = ...,
            initial_apicid: builtins.int = ...,
            fpu: builtins.bool = ...,
            fpu_exception: builtins.bool = ...,
            cpuid_level: builtins.int = ...,
            wp: builtins.bool = ...,
            flags: typing.Optional[typing.Iterable[typing.Text]] = ...,
            bugs: typing.Optional[typing.Iterable[typing.Text]] = ...,
            bogomips: builtins.float = ...,
            tlb_size: typing.Text = ...,
            clflush_size: builtins.int = ...,
            cache_alignment: builtins.int = ...,
            address_sizes: typing.Optional[typing.Iterable[typing.Text]] = ...,
            power_management: typing.Optional[typing.Iterable[typing.Text]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["address_sizes",b"address_sizes","apicid",b"apicid","bogomips",b"bogomips","bugs",b"bugs","cache_alignment",b"cache_alignment","cache_size",b"cache_size","clflush_size",b"clflush_size","core_id",b"core_id","cpu_cores",b"cpu_cores","cpu_family",b"cpu_family","cpu_mhz",b"cpu_mhz","cpuid_level",b"cpuid_level","flags",b"flags","fpu",b"fpu","fpu_exception",b"fpu_exception","initial_apicid",b"initial_apicid","microcode",b"microcode","model",b"model","model_name",b"model_name","physical_id",b"physical_id","power_management",b"power_management","processor",b"processor","siblings",b"siblings","stepping",b"stepping","tlb_size",b"tlb_size","vendor_id",b"vendor_id","wp",b"wp"]) -> None: ...

    class CPULoadInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        USER_FIELD_NUMBER: builtins.int
        NICE_FIELD_NUMBER: builtins.int
        SYSTEM_FIELD_NUMBER: builtins.int
        IDLE_FIELD_NUMBER: builtins.int
        IOWAIT_FIELD_NUMBER: builtins.int
        IRQ_FIELD_NUMBER: builtins.int
        SOFT_IRQ_FIELD_NUMBER: builtins.int
        STEAL_FIELD_NUMBER: builtins.int
        GUEST_FIELD_NUMBER: builtins.int
        GUEST_NICE_FIELD_NUMBER: builtins.int
        user: builtins.int
        nice: builtins.int
        system: builtins.int
        idle: builtins.int
        iowait: builtins.int
        irq: builtins.int
        soft_irq: builtins.int
        steal: builtins.int
        guest: builtins.int
        guest_nice: builtins.int
        def __init__(self,
            *,
            user: builtins.int = ...,
            nice: builtins.int = ...,
            system: builtins.int = ...,
            idle: builtins.int = ...,
            iowait: builtins.int = ...,
            irq: builtins.int = ...,
            soft_irq: builtins.int = ...,
            steal: builtins.int = ...,
            guest: builtins.int = ...,
            guest_nice: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["guest",b"guest","guest_nice",b"guest_nice","idle",b"idle","iowait",b"iowait","irq",b"irq","nice",b"nice","soft_irq",b"soft_irq","steal",b"steal","system",b"system","user",b"user"]) -> None: ...

    LOAD_AVG_1_FIELD_NUMBER: builtins.int
    LOAD_AVG_5_FIELD_NUMBER: builtins.int
    LOAD_AVG_15_FIELD_NUMBER: builtins.int
    PROCESS_CURRENT_FIELD_NUMBER: builtins.int
    PROCESS_ALL_FIELD_NUMBER: builtins.int
    LAST_PID_FIELD_NUMBER: builtins.int
    CORES_FIELD_NUMBER: builtins.int
    LOAD_FIELD_NUMBER: builtins.int
    ALL_LOAD_FIELD_NUMBER: builtins.int
    load_avg_1: builtins.float
    load_avg_5: builtins.float
    load_avg_15: builtins.float
    process_current: builtins.int
    process_all: builtins.int
    last_pid: builtins.int
    @property
    def cores(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GetCPUInfoResponse.CPUCore]: ...
    @property
    def load(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GetCPUInfoResponse.CPULoadInfo]: ...
    @property
    def all_load(self) -> global___GetCPUInfoResponse.CPULoadInfo: ...
    def __init__(self,
        *,
        load_avg_1: builtins.float = ...,
        load_avg_5: builtins.float = ...,
        load_avg_15: builtins.float = ...,
        process_current: builtins.int = ...,
        process_all: builtins.int = ...,
        last_pid: builtins.int = ...,
        cores: typing.Optional[typing.Iterable[global___GetCPUInfoResponse.CPUCore]] = ...,
        load: typing.Optional[typing.Iterable[global___GetCPUInfoResponse.CPULoadInfo]] = ...,
        all_load: typing.Optional[global___GetCPUInfoResponse.CPULoadInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["all_load",b"all_load"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["all_load",b"all_load","cores",b"cores","last_pid",b"last_pid","load",b"load","load_avg_1",b"load_avg_1","load_avg_15",b"load_avg_15","load_avg_5",b"load_avg_5","process_all",b"process_all","process_current",b"process_current"]) -> None: ...
global___GetCPUInfoResponse = GetCPUInfoResponse

class GetNetInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class EthInterface(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class Receive(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            BYTES_FIELD_NUMBER: builtins.int
            PACKETS_FIELD_NUMBER: builtins.int
            ERRORS_FIELD_NUMBER: builtins.int
            DROP_FIELD_NUMBER: builtins.int
            FIFO_FIELD_NUMBER: builtins.int
            FRAME_FIELD_NUMBER: builtins.int
            COMPRESSED_FIELD_NUMBER: builtins.int
            MULTICAST_FIELD_NUMBER: builtins.int
            bytes: builtins.int
            packets: builtins.int
            errors: builtins.int
            drop: builtins.int
            fifo: builtins.int
            frame: builtins.int
            compressed: builtins.int
            multicast: builtins.int
            def __init__(self,
                *,
                bytes: builtins.int = ...,
                packets: builtins.int = ...,
                errors: builtins.int = ...,
                drop: builtins.int = ...,
                fifo: builtins.int = ...,
                frame: builtins.int = ...,
                compressed: builtins.int = ...,
                multicast: builtins.int = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["bytes",b"bytes","compressed",b"compressed","drop",b"drop","errors",b"errors","fifo",b"fifo","frame",b"frame","multicast",b"multicast","packets",b"packets"]) -> None: ...

        class Transmit(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            BYTES_FIELD_NUMBER: builtins.int
            PACKETS_FIELD_NUMBER: builtins.int
            ERRORS_FIELD_NUMBER: builtins.int
            DROP_FIELD_NUMBER: builtins.int
            FIFO_FIELD_NUMBER: builtins.int
            COLLS_FIELD_NUMBER: builtins.int
            CARRIER_FIELD_NUMBER: builtins.int
            COMPRESSED_FIELD_NUMBER: builtins.int
            bytes: builtins.int
            packets: builtins.int
            errors: builtins.int
            drop: builtins.int
            fifo: builtins.int
            colls: builtins.int
            carrier: builtins.int
            compressed: builtins.int
            def __init__(self,
                *,
                bytes: builtins.int = ...,
                packets: builtins.int = ...,
                errors: builtins.int = ...,
                drop: builtins.int = ...,
                fifo: builtins.int = ...,
                colls: builtins.int = ...,
                carrier: builtins.int = ...,
                compressed: builtins.int = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["bytes",b"bytes","carrier",b"carrier","colls",b"colls","compressed",b"compressed","drop",b"drop","errors",b"errors","fifo",b"fifo","packets",b"packets"]) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        RECEIVE_FIELD_NUMBER: builtins.int
        TRANSMIT_FIELD_NUMBER: builtins.int
        name: typing.Text
        @property
        def receive(self) -> global___GetNetInfoResponse.EthInterface.Receive: ...
        @property
        def transmit(self) -> global___GetNetInfoResponse.EthInterface.Transmit: ...
        def __init__(self,
            *,
            name: typing.Text = ...,
            receive: typing.Optional[global___GetNetInfoResponse.EthInterface.Receive] = ...,
            transmit: typing.Optional[global___GetNetInfoResponse.EthInterface.Transmit] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["receive",b"receive","transmit",b"transmit"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name",b"name","receive",b"receive","transmit",b"transmit"]) -> None: ...

    INTERFACES_FIELD_NUMBER: builtins.int
    @property
    def interfaces(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GetNetInfoResponse.EthInterface]: ...
    def __init__(self,
        *,
        interfaces: typing.Optional[typing.Iterable[global___GetNetInfoResponse.EthInterface]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["interfaces",b"interfaces"]) -> None: ...
global___GetNetInfoResponse = GetNetInfoResponse
