"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetSystemInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OS_NAME_FIELD_NUMBER: builtins.int
    OS_RELEASE_FIELD_NUMBER: builtins.int
    UPTIME_FIELD_NUMBER: builtins.int
    os_name: typing.Text
    os_release: typing.Text
    uptime: builtins.float
    def __init__(self,
        *,
        os_name: typing.Text = ...,
        os_release: typing.Text = ...,
        uptime: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["os_name",b"os_name","os_release",b"os_release","uptime",b"uptime"]) -> None: ...
global___GetSystemInfoResponse = GetSystemInfoResponse
