# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lrcp.grpc_data import base_pb2 as lrcp_dot_grpc__data_dot_base__pb2
from lrcp.grpc_data import client_pb2 as lrcp_dot_grpc__data_dot_client__pb2


class ClientServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ClientServicer/Ping',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.FromString,
                )
        self.GetSystemInfo = channel.unary_unary(
                '/ClientServicer/GetSystemInfo',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_client__pb2.GetSystemInfoResponse.FromString,
                )
        self.GetMemoryInfo = channel.unary_unary(
                '/ClientServicer/GetMemoryInfo',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_base__pb2.GetMemoryInfoResponse.FromString,
                )
        self.GetCPUInfo = channel.unary_unary(
                '/ClientServicer/GetCPUInfo',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_base__pb2.GetCPUInfoResponse.FromString,
                )
        self.GetNetInfo = channel.unary_unary(
                '/ClientServicer/GetNetInfo',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_base__pb2.GetNetInfoResponse.FromString,
                )


class ClientServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCPUInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.SerializeToString,
            ),
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_client__pb2.GetSystemInfoResponse.SerializeToString,
            ),
            'GetMemoryInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryInfo,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_base__pb2.GetMemoryInfoResponse.SerializeToString,
            ),
            'GetCPUInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCPUInfo,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_base__pb2.GetCPUInfoResponse.SerializeToString,
            ),
            'GetNetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetInfo,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_base__pb2.GetNetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientServicer/Ping',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientServicer/GetSystemInfo',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_client__pb2.GetSystemInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMemoryInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientServicer/GetMemoryInfo',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_base__pb2.GetMemoryInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCPUInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientServicer/GetCPUInfo',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_base__pb2.GetCPUInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientServicer/GetNetInfo',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_base__pb2.GetNetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
