# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lrcp/grpc_data/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lrcp.grpc_data import base_pb2 as lrcp_dot_grpc__data_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blrcp/grpc_data/client.proto\x1a\x19lrcp/grpc_data/base.proto\"L\n\x15GetSystemInfoResponse\x12\x0f\n\x07os_name\x18\x01 \x01(\t\x12\x12\n\nos_release\x18\x02 \x01(\t\x12\x0e\n\x06uptime\x18\x03 \x01(\x02\x32\x8f\x02\n\x0e\x43lientServicer\x12%\n\x04Ping\x12\x0c.BaseRequest\x1a\r.BaseResponse\"\x00\x12\x37\n\rGetSystemInfo\x12\x0c.BaseRequest\x1a\x16.GetSystemInfoResponse\"\x00\x12\x37\n\rGetMemoryInfo\x12\x0c.BaseRequest\x1a\x16.GetMemoryInfoResponse\"\x00\x12\x31\n\nGetCPUInfo\x12\x0c.BaseRequest\x1a\x13.GetCPUInfoResponse\"\x00\x12\x31\n\nGetNetInfo\x12\x0c.BaseRequest\x1a\x13.GetNetInfoResponse\"\x00\x62\x06proto3')



_GETSYSTEMINFORESPONSE = DESCRIPTOR.message_types_by_name['GetSystemInfoResponse']
GetSystemInfoResponse = _reflection.GeneratedProtocolMessageType('GetSystemInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSYSTEMINFORESPONSE,
  '__module__' : 'lrcp.grpc_data.client_pb2'
  # @@protoc_insertion_point(class_scope:GetSystemInfoResponse)
  })
_sym_db.RegisterMessage(GetSystemInfoResponse)

_CLIENTSERVICER = DESCRIPTOR.services_by_name['ClientServicer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSYSTEMINFORESPONSE._serialized_start=58
  _GETSYSTEMINFORESPONSE._serialized_end=134
  _CLIENTSERVICER._serialized_start=137
  _CLIENTSERVICER._serialized_end=408
# @@protoc_insertion_point(module_scope)
