"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import lrcp.grpc_data.base_pb2
import lrcp.grpc_data.server_pb2

class ServerServicerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Ping: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.base_pb2.BaseRequest,
        lrcp.grpc_data.base_pb2.BaseResponse]

    CreateServer: grpc.UnaryUnaryMultiCallable[
        lrcp.grpc_data.server_pb2.CreateServerRequest,
        lrcp.grpc_data.server_pb2.CreateServerResponse]


class ServerServicerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Ping(self,
        request: lrcp.grpc_data.base_pb2.BaseRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.base_pb2.BaseResponse: ...

    @abc.abstractmethod
    def CreateServer(self,
        request: lrcp.grpc_data.server_pb2.CreateServerRequest,
        context: grpc.ServicerContext,
    ) -> lrcp.grpc_data.server_pb2.CreateServerResponse: ...


def add_ServerServicerServicer_to_server(servicer: ServerServicerServicer, server: grpc.Server) -> None: ...
