# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lrcp.grpc_data import base_pb2 as lrcp_dot_grpc__data_dot_base__pb2
from lrcp.grpc_data import server_pb2 as lrcp_dot_grpc__data_dot_server__pb2


class ServerServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ServerServicer/Ping',
                request_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.FromString,
                )
        self.CreateServer = channel.unary_unary(
                '/ServerServicer/CreateServer',
                request_serializer=lrcp_dot_grpc__data_dot_server__pb2.CreateServerRequest.SerializeToString,
                response_deserializer=lrcp_dot_grpc__data_dot_server__pb2.CreateServerResponse.FromString,
                )


class ServerServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.SerializeToString,
            ),
            'CreateServer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServer,
                    request_deserializer=lrcp_dot_grpc__data_dot_server__pb2.CreateServerRequest.FromString,
                    response_serializer=lrcp_dot_grpc__data_dot_server__pb2.CreateServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServerServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerServicer/Ping',
            lrcp_dot_grpc__data_dot_base__pb2.BaseRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_base__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerServicer/CreateServer',
            lrcp_dot_grpc__data_dot_server__pb2.CreateServerRequest.SerializeToString,
            lrcp_dot_grpc__data_dot_server__pb2.CreateServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
