"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CreateServerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    access_token: typing.Text
    ip: typing.Text
    port: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        access_token: typing.Text = ...,
        ip: typing.Text = ...,
        port: builtins.int = ...,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["access_token",b"access_token","ip",b"ip","name",b"name","port",b"port"]) -> None: ...
global___CreateServerRequest = CreateServerRequest

class CreateServerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    API_KEY_FIELD_NUMBER: builtins.int
    api_key: typing.Text
    def __init__(self,
        *,
        api_key: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key",b"api_key"]) -> None: ...
global___CreateServerResponse = CreateServerResponse
